keys:
  - &server age1tfcfat3y9uekdw8u2ln4az4uqfznk25ntarte34292rz0zw3zy6qjcqqth
  - &laptop age1qdslghtpq4zew5jkc6c23r9petqq3mc23xccn6hqk2qg26sx9prqdutrd3
  - &pc age1lzxxtwcxvk9slq5vn2rw35gm9r93c0w0hg0wlwgn7ctu89wxpums0r8ke7

creation_rules:
  - path_regex: secrets/.+.secret
    key_groups:
      - age:
          - *server
          - *laptop
          - *pc
