keys:
  - &server age1tfcfat3y9uekdw8u2ln4az4uqfznk25ntarte34292rz0zw3zy6qjcqqth
  - &laptop age17ajces2ka639rq9am5c707nz0qgqste5a25hky5mcraargryvp7s6esm7p
  - &tom age1pjgmdxkj6zvn5hpjwd4mlv2jw89mk78luuetdcjqtmaq6r88juwshyjqal

creation_rules:
  - path_regex: secrets/[^/]+.secret
    key_groups:
      - age:
          - *server
          - *laptop
  - path_regex: secrets/[^/]+.shared.secret
    key_groups:
      - age:
          - *server
          - *laptop
          - *tom
